[package]
name = "debug"
version = "0.1.0"
authors = ["Pythas <pythas@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
nes = { path = "../nes" }

[dependencies.sdl2]
version = "0.33"
default-features = false
features = ["ttf"]